blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/curiosum-dev/permit/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://hexdocs.pm/permit_absinthe
    about: Read the official Permit.Absinthe documentation
  - name: 🎯 Absinthe Documentation
    url: https://hexdocs.pm/absinthe
    about: Read the Absinthe GraphQL documentation
  - name: 📝 Curiosum Blog
    url: https://curiosum.com/blog
    about: Read blog posts about Permit updates and tutorials
  - name: 🏢 Contact Curiosum
    url: https://curiosum.com/contact
    about: Get in touch with the team behind Permit
